# SOMC target definitions
ifeq ($(CONFIG_MACH_SONY_PDX223),y)
SOMC_TARGET_PRODUCT := pdx223
endif
ifeq ($(CONFIG_MACH_SONY_PDX224),y)
SOMC_TARGET_PRODUCT := pdx224
endif
SOMC_TARGET_OPERATOR := generic
SOMC_PLATFORM := nagara

ifeq ($(CONFIG_TARGET), neo_le)
dtbo-$(CONFIG_ARCH_NEO) += display/neo-sde.dtbo \
                display/neo-sde-display-idp-overlay.dtbo \
                display/neo-sde-display-qxr-overlay.dtbo \
                display/foreseer-sde-display-qxr-overlay.dtbo
endif

ifeq ($(CONFIG_TARGET), neo_la)
dtbo-$(CONFIG_ARCH_NEO) += display/neo-sde.dtbo \
                display/neo_la-sde-no-display-overlay.dtbo \
                display/neo_luna-v2-sde-display-idp-overlay.dtbo \
		display/neo_luna-v2-sde-display-sg-idp-overlay.dtbo
endif

ifneq ($(CONFIG_ARCH_QTI_VM), y)
dtbo-$(CONFIG_ARCH_WAIPIO) += display/waipio-sde.dtbo \
		display/waipio-sde-display-mtp-overlay.dtbo \
		display/waipio-sde-display-cphy-mtp-overlay.dtbo \
		display/waipio-sde-display-mtp-68disp-overlay.dtbo \
		display/waipio-sde-display-cdp-overlay.dtbo \
		display/waipio-sde-display-qrd-overlay.dtbo \
		display/waipio-sde-display-hdk-overlay.dtbo \
		display/waipio-sde-display-waipio-lemur-cdp-overlay.dtbo \
		display/waipio-sde-display-waipio-lemur-mtp-overlay.dtbo \
		display/waipio-sde-display-rumi-overlay.dtbo
endif

ifneq ($(CONFIG_ARCH_QTI_VM), y)
dtbo-$(CONFIG_ARCH_CAPE) += display/cape-sde.dtbo \
		display/cape-sde-display-atp-overlay.dtbo \
		display/cape-sde-display-cdp-overlay.dtbo \
		display/cape-sde-display-cdp-qhd-overlay.dtbo \
		display/cape-sde-display-mtp-overlay.dtbo \
		display/cape-sde-display-mtp-120fps-overlay.dtbo \
		display/cape-sde-display-mtp-nodisplay-overlay.dtbo \
		display/cape-sde-display-qrd-overlay.dtbo
endif

ifneq ($(CONFIG_ARCH_QTI_VM), y)
dtbo-$(CONFIG_ARCH_DIWALI) += display/diwali-sde.dtbo \
		display/diwali-sde-display-atp-overlay.dtbo \
		display/diwali-sde-display-idp-overlay.dtbo \
		display/diwali-sde-display-idp-amoled-overlay.dtbo \
		display/diwali-sde-display-qrd-overlay.dtbo \
		display/diwali-sde-display-rumi-overlay.dtbo
endif

ifneq ($(CONFIG_ARCH_QTI_VM), y)
dtbo-$(CONFIG_ARCH_PARROT) += display/parrot-sde.dtbo \
		display/parrot-sde-display-atp-overlay.dtbo \
		display/parrot-sde-display-idp-overlay.dtbo \
		display/parrot-sde-display-idp-amoled-overlay.dtbo \
		display/parrot-sde-display-rumi-overlay.dtbo \
		display/parrot-sde-display-qrd-overlay.dtbo
endif

ifneq ($(CONFIG_ARCH_QTI_VM), y)
dtbo-$(CONFIG_ARCH_RAVELIN) += display/ravelin-sde.dtbo \
		display/ravelin-sde-display-atp-overlay.dtbo \
		display/ravelin-sde-display-idp-overlay.dtbo \
		display/ravelin-sde-display-idp-amoled-overlay.dtbo \
		display/ravelin-sde-display-rumi-overlay.dtbo \
		display/ravelin-sde-display-qrd-overlay.dtbo
endif

# SOMC product operator
SOMC_PRODUCT_OPERATOR = $(SOMC_TARGET_PRODUCT)_$(SOMC_TARGET_OPERATOR)

# pdx223
ifneq ($(filter pdx223_generic,$(SOMC_PRODUCT_OPERATOR)),)
dtb-y += display/waipio-sde.dtbo

dtbo-y += display/waipio-sde.dtbo \
	  display/waipio-sde-display-pdx223-overlay.dts
endif

# pdx224
ifneq ($(filter pdx224_generic,$(SOMC_PRODUCT_OPERATOR)),)
dtb-y += display/waipio-sde.dtbo

dtbo-y += display/waipio-sde.dtbo \
          display/waipio-sde-display-pdx224-overlay.dts
endif


always-y    := $(dtb-y) $(dtbo-y)
subdir-y    := $(dts-dirs)
clean-files    := *.dtb *.dtbo
