DTC_INCLUDE += $(srctree)/../sm8450-modules/qcom/opensource/audio-kernel/include
KBUILD_DTC_INCLUDE += $(srctree)/../sm8450-modules/qcom/opensource/audio-kernel/include

# SOMC target definitions
ifeq ($(CONFIG_MACH_SONY_PDX223),y)
SOMC_TARGET_PRODUCT := pdx223
endif
ifeq ($(CONFIG_MACH_SONY_PDX224),y)
SOMC_TARGET_PRODUCT := pdx224
endif
SOMC_TARGET_OPERATOR := generic
SOMC_PLATFORM := nagara

# SOMC product operator
SOMC_PRODUCT_OPERATOR = $(SOMC_TARGET_PRODUCT)_$(SOMC_TARGET_OPERATOR)

ifeq ($(CONFIG_ARCH_WAIPIO), y)
ifeq ($(SOMC_PRODUCT_OPERATOR),pdx223_generic)
dtbo-y += waipio-audio.dtbo \
	  somc-nagara-audio-pdx223.dtbo
endif
ifeq ($(SOMC_PRODUCT_OPERATOR),pdx224_generic)
dtbo-y += waipio-audio.dtbo \
          somc-nagara-audio-pdx224.dtbo
endif
else
dtbo-y += waipio-audio.dtbo \
          waipio-audio-cdp.dtbo \
          waipio-audio-mtp.dtbo \
          waipio-audio-qrd.dtbo \
          waipio-audio-atp.dtbo \
          waipio-audio-rumi.dtbo \
          waipio-audio-hdk.dtbo
endif

 always-y    := $(dtb-y) $(dtbo-y)
 subdir-y    := $(dts-dirs)
 clean-files    := *.dtb *.dtbo
